apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kube-data
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: NodePort
  selector:
    app: postgres

