version: '3' 
services: 
  service2: 
    image: busybox 
    command: sleep infinity
    depends_on:
      - "service3" 
  service3:
    image: busybox
    command: sleep infinity


networks:
  default:
    external:
      name: external-network
